# site settings
title: Kyle
subtitle: AKA Giantpizzahead
email: giantpizzahead@gmail.com
description: An MIT freshman looking to make the world a better place using the latest breakthroughs in computer science.
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kylefu.me" # the base hostname & protocol for your site
author: Kyle
street_address: 1234 Somewhere Road
city: Someplace
state: IDK
zip_code: 12345
country: United States of America
phone: (123) 456-7890

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/Giantpizzahead
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn: https://www.linkedin.com/in/kyle-fu-us/
  Twitter:
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
